#!/bin/bash
# https://wiki.archlinux.org/title/Pacman/Tips_and_tricks
expac -H M "%011m\t%-20n\t%10d" $(comm -23 <(pacman -Qqen | sort) <({ pacman -Qqg base-devel; expac -l '\n' '%E' base; } | sort | uniq)) | sort -n
